sudo: false
language: haskell
ghc:
  - 7.8
install:
  - cabal install packdeps
  - cabal sandbox init
  - cabal install --enable-tests --only-dependencies
script:
  - packdeps tempus.cabal
  - cabal configure --enable-tests
  - cabal build
  - cabal test